title: 小林子的个人博客
email: xiaolintsang@163.com
description: >- # this means to ignore newlines until "baseurl:"
  学而，时习之.
baseurl:           ""
url:               "https://okfine.top"

# Social Profiles
github_username:   xiaolinzi12

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
